workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never  # disable detached pipelines
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
    - if: '$CI_OPEN_MERGE_REQUESTS'
      when: always

check_style:
  image: node:18-alpine
  script:
    - npm install -g markdownlint-cli2 markdownlint-cli2-formatter-junit
    - markdownlint-cli2-config .markdownlint-cli2.yaml "**/*.md"
  artifacts:
    when: always
    reports:
      junit:
        - markdown-linting-errors.xml

build_wiki:
  image: ubuntu:20.04
  stage: deploy
  script:
    - apt -qq update
    - apt -qq install git -y
    - cd ~
    - git clone https://$WikiAccessUser:$WikiAccessPwd@gitlab.internal.d-fine.dev/trainings/basis-it-training.wiki.git
    - cd basis-it-training.wiki
    - git config user.name "CI Bot"
    - git config user.email "ci_bot@example.com"
    - rm -rf *
    - cp -rv $CI_PROJECT_DIR/content/* .
    - git add .
    - git commit -m "$CI_COMMIT_MESSAGE"
    - git push https://$WikiAccessUser:$WikiAccessPwd@gitlab.internal.d-fine.dev/trainings/basis-it-training.wiki.git
  only:
    refs:
      - master
    changes:
      - content/*
      - content/**/*
    variables:
      - $WikiAccessPwd
