name: Lint Markdown files
on:
  pull_request:

jobs:
  check_style:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install MarkdownlintCLI2
      run: npm install -g markdownlint-cli2 markdownlint-cli2-formatter-junit
    - name: Run MarkdownlintCLI2
      run: markdownlint-cli2-config .markdownlint-cli2.yaml "**/*.md"
    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v3
      if: success() || failure()
      with:
        report_paths: 'markdown-linting-errors.xml'
